const holidaysArr = [
  "christmas",
  "reindeer",
  "mistletoe",
  "holly",
  "santa",
  "claus",
  "holiday",
  "jingle",
  "bells",
  "frosty",
  "snow",
  "snowman",
  "feliz navidad",
  "st. nick",
  "do you hear what i hear",
  "rudolph",
  "silent night",
  "sleigh",
  "drummer",
  "toys",
  "winter",
  "wonderland",
  "most wonderful time of the year",
  "time of year",
  "merry",
];

module.exports = { holidaysArr };
